### ISSUE TITLE
推理速度为何这么慢

### ISSUE THREAD

**Issue by Virtual1257** [codefuse-ai/codefuse#7]
我在nvidia V100 上部署了CodeFuse-QWen-14B,但是推理的速度很慢，一次回答可能需要几十分钟，这是什么原因？

**Comment by Think-dfrent** [comment]
我用的就是魔塔社区里的示例
```py
import torch
from modelscope import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    snapshot_download
)
model_dir = snapshot_download('codefuse-ai/CodeFuse-QWen-14B',revision = 'v1.0.0')
tokenizer = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True)
tokenizer.padding_side = "left"
tokenizer.pad_token_id = tokenizer.convert_tokens_to_ids("<|endoftext|>")
tokenizer.eos_token_id = tokenizer.convert_tokens_to_ids("<|endoftext|>")
tokenizer.pad_token = "<|endoftext|>"
tokenizer.eos_token = "<|endoftext|>"
# try 4bit loading if cuda memory not enough
model = AutoModelForCausalLM.from_pretrained(model_dir,
                                             trust_remote_code=True,
                                             load_in_4bit=False,
                                             device_map="auto",
                                             torch_dtype=torch.bfloat16)
model.eval()

HUMAN_ROLE_START_TAG = "<s>human\n"
BOT_ROLE_START_TAG = "<s>bot\n"

text = f"{HUMAN_ROLE_START_TAG}write a python function of quick sort.\n{BOT_ROLE_START_TAG}" 
inputs = tokenizer(text, return_tensors='pt', padding=True, add_special_tokens=False).to("cuda")
outputs = model.generate(
        inputs=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        max_new_tokens=512,
        top_p=0.95,
        temperature=0.1,
        do_sample=True,
        eos_token_id=tokenizer.eos_token_id,
        pad_token_id=tokenizer.pad_token_id
    )
gen_text = tokenizer.batch_decode(outputs[:, inputs["input_ids"].shape[1]:], skip_special_tokens=True)
print(gen_text)
```

**Comment by chencyudel** [comment]
> 
> ```python
>
> # try 4bit loading if cuda memory not enough
> model = AutoModelForCausalLM.from_pretrained(model_dir,
>                                              trust_remote_code=True,
>                                              load_in_4bit=False,
>                                              device_map="auto",
>                                              torch_dtype=torch.float16)
>
> ```

You may wanna try torch_dtype=torch.float16, nvidia v100 gpu may not support bf16.

**Comment by Think-dfrent** [comment]
> > ```
> > 
> > # try 4bit loading if cuda memory not enough
> > model = AutoModelForCausalLM.from_pretrained(model_dir,
> >                                              trust_remote_code=True,
> >                                              load_in_4bit=False,
> >                                              device_map="auto",
> >                                              torch_dtype=torch.float16)
> > ```
> 
> You may wanna try torch_dtype=torch.float16, nvidia v100 gpu may not support bf16. @Think-dfrent

我使用torch_dtype=torch.float16参数后仍然没有改善，有什么方法可以将bf16的模型转为f16吗？

**Comment by chencyudel** [comment]
> > > ```
> > > 
> > > # try 4bit loading if cuda memory not enough
> > > model = AutoModelForCausalLM.from_pretrained(model_dir,
> > >                                              trust_remote_code=True,
> > >                                              load_in_4bit=False,
> > >                                              device_map="auto",
> > >                                              torch_dtype=torch.float16)
> > > ```
> > 
> > 
> > You may wanna try torch_dtype=torch.float16, nvidia v100 gpu may not support bf16. @Think-dfrent
> 
> 我使用torch_dtype=torch.float16参数后仍然没有改善，有什么方法可以将bf16的模型转为f16吗？

Have you check command nvidia-smi and make sure you are using only gpu for inferencing
