### ISSUE TITLE
modelscope 加载模型报错

### ISSUE THREAD

**Issue by zhangji85** [codefuse-ai/codefuse#8]
modelscope 加载模型报错，提示找不到文件pytorch_model-00001-of-00007.bin ，但codefuse-ai/CodeFuse-CodeLlama-34B-4bits 中并没有该文件

**Comment by twelveand0** [comment]
你好，你的load代码和环境配置能发一下吗

**Comment by zhangji85** [comment]
> 你好，你的load代码和环境配置能发一下吗
加载代码是：
from modelscope.models import Model


# 加载模型和预处理器
# 传入模型ID 或 模型目录
model = Model.from_pretrained(model_name_or_path='codefuse-ai/CodeFuse-CodeLlama-34B-4bits', device='cuda:0')

**Comment by twelveand0** [comment]
这个模型使用gpt-q量化过的，不要直接这样load，可以用下面这段代码load:

**Comment by twelveand0** [comment]
这个模型是用gpt-q量化过的，可以用下面这段代码load:

**Comment by twelveand0** [comment]
这个模型是用gpt-q量化过的，可以用下面这段代码load: 
def load_model_tokenizer(model_name_or_local_path):
```python
    """
    Load model and tokenizer based on the given model name or local path of the downloaded model.
    """
    tokenizer = AutoTokenizer.from_pretrained(model_name_or_local_path, 
                                              trust_remote_code=True, 
                                              use_fast=False,
                                              lagecy=False)
    tokenizer.padding_side = "left"

    model = AutoGPTQForCausalLM.from_quantized(model_name_or_local_path, 
                                                inject_fused_attention=False,
                                                inject_fused_mlp=False,
                                                use_cuda_fp16=True,
                                                disable_exllama=False,
                                                device_map='auto'   # Support multi-gpus
                                              )
    return model, tokenizer
```

**Comment by zhangji85** [comment]
> 这个模型是用gpt-q量化过的，可以用下面这段代码load: def load_model_tokenizer(model_name_or_local_path):
> 
> ```python
>     """
>     Load model and tokenizer based on the given model name or local path of the downloaded model.
>     """
>     tokenizer = AutoTokenizer.from_pretrained(model_name_or_local_path, 
>                                               trust_remote_code=True, 
>                                               use_fast=False,
>                                               lagecy=False)
>     tokenizer.padding_side = "left"
> 
>     model = AutoGPTQForCausalLM.from_quantized(model_name_or_local_path, 
>                                                 inject_fused_attention=False,
>                                                 inject_fused_mlp=False,
>                                                 use_cuda_fp16=True,
>                                                 disable_exllama=False,
>                                                 device_map='auto'   # Support multi-gpus
>                                               )
>     return model, tokenizer
> ```

好的，这个我测试过，可以正常加载

**Comment by twelveand0** [comment]
您好，您是否还有进一步的问题，如果没有我将关闭这个issue

**Comment by twelveand0** [comment]
You can re-open it if you have more question about this. Thanks
