### ISSUE TITLE
CodeFuse插件是否支持本地代码大模型

### ISSUE THREAD

**Issue by tianyouyangying** [codefuse-ai/codefuse#9]
CodeFuse插件是直接对接在线的codefuse，能够通过本地部署codefuse-codellama-34b-4bits，实现代码插件，因为有些机器开发项目是离线或则涉密的。

**Comment by ss41979310** [comment]
代码补全插件涉及较多工程开发工作，包括服务端和插件端，暂无全链路开源计划。如果有商业化部署需求，请联系蚂蚁数字科技。联系方式已私聊。
